import type { ScriptedTurn } from "../types";
import { catanTurnNarrative } from "./narrative";

export { developmentCardLabels, resourceLabels } from "./labels";

const [turn1, turn2, turn3, turn4, turn5, turn6] = catanTurnNarrative;

export const scriptedTurns: ScriptedTurn[] = [
  {
    turn: 1,
    title: turn1.title,
    phase: "opening",
    dice: [3, 3],
    robber: {
      tileId: 4,
      note: turn1.robberNote,
      targetOwner: "player",
    },
    production: {
      note: turn1.productionNote,
      activatedTileIds: [3],
      player: { ore: 1 },
      opponents: { leah: { ore: 1 } },
    },
    mood: turn1.mood,
    sceneLine: turn1.sceneLine,
    actions: [
      {
        id: "steady-harvest",
        label: turn1.actions["steady-harvest"].label,
        description: turn1.actions["steady-harvest"].description,
        target: { kind: "node", id: 0 },
        gain: { wood: 1, brick: 1, grain: 1, wool: 1 },
        pointGain: 0,
        steal: "wood",
        stealBy: "leah",
        playerLine: turn1.actions["steady-harvest"].playerLine,
        npcLine: turn1.actions["steady-harvest"].npcLine,
        opponentGain: { leah: 1, sam: 1 },
        recommended: true,
      },
      {
        id: "force-settlement",
        label: turn1.actions["force-settlement"].label,
        description: turn1.actions["force-settlement"].description,
        target: { kind: "node", id: 3 },
        build: { kind: "settlement" },
        spend: { wood: 1, brick: 1, grain: 1, wool: 1 },
        gain: { ore: 1 },
        pointGain: 1,
        playerLine: turn1.actions["force-settlement"].playerLine,
        npcLine: turn1.actions["force-settlement"].npcLine,
        opponentGain: { leah: 1 },
      },
    ],
  },
  {
    turn: 2,
    title: turn2.title,
    phase: "opening",
    dice: [4, 4],
    robber: {
      tileId: 1,
      note: turn2.robberNote,
      targetOwner: "player",
    },
    production: {
      note: turn2.productionNote,
      activatedTileIds: [1],
      player: { grain: 1 },
      opponents: { leah: { grain: 1 } },
    },
    mood: turn2.mood,
    sceneLine: turn2.sceneLine,
    actions: [
      {
        id: "careful-setup",
        label: turn2.actions["careful-setup"].label,
        description: turn2.actions["careful-setup"].description,
        target: { kind: "node", id: 0 },
        gainDevelopmentCards: { knight: 1 },
        gain: { brick: 1, grain: 1, ore: 1, wool: 1 },
        pointGain: 0,
        steal: "grain",
        stealBy: "leah",
        playerLine: turn2.actions["careful-setup"].playerLine,
        npcLine: turn2.actions["careful-setup"].npcLine,
        opponentGain: { sam: 1 },
        recommended: true,
      },
      {
        id: "hold-the-road",
        label: turn2.actions["hold-the-road"].label,
        description: turn2.actions["hold-the-road"].description,
        target: { kind: "road", id: 4 },
        build: { kind: "road" },
        spend: { wood: 1, brick: 1 },
        gain: { grain: 1, wool: 1 },
        pointGain: 1,
        playerLine: turn2.actions["hold-the-road"].playerLine,
        npcLine: turn2.actions["hold-the-road"].npcLine,
        opponentGain: { sam: 1 },
      },
    ],
  },
  {
    turn: 3,
    title: turn3.title,
    phase: "turning",
    dice: [5, 4],
    robber: {
      tileId: 2,
      note: turn3.robberNote,
      targetOwner: "sam",
    },
    production: {
      note: turn3.productionNote,
      activatedTileIds: [4],
      player: { wool: 1 },
      opponents: { sam: { wool: 1 } },
    },
    mood: turn3.mood,
    sceneLine: turn3.sceneLine,
    actions: [
      {
        id: "harbor-trade",
        label: turn3.actions["harbor-trade"].label,
        description: turn3.actions["harbor-trade"].description,
        target: { kind: "road", id: 5 },
        build: { kind: "road" },
        gainDevelopmentCards: { roadBuilding: 1 },
        useDevelopmentCard: "knight",
        gain: { grain: 2, ore: 2 },
        pointGain: 1,
        playerLine: turn3.actions["harbor-trade"].playerLine,
        npcLine: turn3.actions["harbor-trade"].npcLine,
        recommended: true,
      },
      {
        id: "counter-expand",
        label: turn3.actions["counter-expand"].label,
        description: turn3.actions["counter-expand"].description,
        target: { kind: "node", id: 4 },
        build: { kind: "settlement" },
        spend: { wood: 1, brick: 1, grain: 1, wool: 1 },
        gain: { ore: 1 },
        pointGain: 2,
        playerLine: turn3.actions["counter-expand"].playerLine,
        npcLine: turn3.actions["counter-expand"].npcLine,
      },
    ],
  },
  {
    turn: 4,
    title: turn4.title,
    phase: "closing",
    dice: [5, 5],
    robber: {
      tileId: 5,
      note: turn4.robberNote,
      targetOwner: "leah",
    },
    production: {
      note: turn4.productionNote,
      activatedTileIds: [2],
      player: { brick: 1 },
      opponents: {},
    },
    mood: turn4.mood,
    sceneLine: turn4.sceneLine,
    actions: [
      {
        id: "upgrade-city",
        label: turn4.actions["upgrade-city"].label,
        description: turn4.actions["upgrade-city"].description,
        target: { kind: "node", id: 0 },
        build: { kind: "city" },
        spend: { grain: 2, ore: 3 },
        gain: { wool: 1 },
        pointGain: 2,
        playerLine: turn4.actions["upgrade-city"].playerLine,
        npcLine: turn4.actions["upgrade-city"].npcLine,
        recommended: true,
      },
      {
        id: "development-chain",
        label: turn4.actions["development-chain"].label,
        description: turn4.actions["development-chain"].description,
        target: { kind: "road", id: 6 },
        build: { kind: "road" },
        useDevelopmentCard: "roadBuilding",
        spend: { ore: 1, grain: 1, wool: 1 },
        gain: { wood: 1, brick: 1, grain: 1 },
        pointGain: 2,
        playerLine: turn4.actions["development-chain"].playerLine,
        npcLine: turn4.actions["development-chain"].npcLine,
      },
    ],
  },
  {
    turn: 5,
    title: turn5.title,
    phase: "closing",
    dice: [1, 4],
    robber: {
      tileId: 0,
      note: turn5.robberNote,
      targetOwner: "leah",
    },
    production: {
      note: turn5.productionNote,
      activatedTileIds: [0],
      player: { wood: 1 },
      opponents: { leah: { wood: 1 } },
    },
    mood: turn5.mood,
    sceneLine: turn5.sceneLine,
    actions: [
      {
        id: "longest-road",
        label: turn5.actions["longest-road"].label,
        description: turn5.actions["longest-road"].description,
        target: { kind: "road", id: 6 },
        build: { kind: "road" },
        spend: { wood: 2, brick: 2 },
        gain: { grain: 1 },
        pointGain: 2,
        playerLine: turn5.actions["longest-road"].playerLine,
        npcLine: turn5.actions["longest-road"].npcLine,
        recommended: true,
      },
      {
        id: "grand-harvest",
        label: turn5.actions["grand-harvest"].label,
        description: turn5.actions["grand-harvest"].description,
        target: { kind: "node", id: 4 },
        gainDevelopmentCards: { harvest: 1 },
        gain: { wood: 1, brick: 1, grain: 1, ore: 1, wool: 1 },
        pointGain: 1,
        playerLine: turn5.actions["grand-harvest"].playerLine,
        npcLine: turn5.actions["grand-harvest"].npcLine,
      },
    ],
  },
  {
    turn: 6,
    title: turn6.title,
    phase: "closing",
    dice: [2, 2],
    robber: {
      tileId: 3,
      note: turn6.robberNote,
      targetOwner: "sam",
    },
    production: {
      note: turn6.productionNote,
      activatedTileIds: [5],
      player: { wood: 1 },
      opponents: {},
    },
    mood: turn6.mood,
    sceneLine: turn6.sceneLine,
    actions: [
      {
        id: "final-toast",
        label: turn6.actions["final-toast"].label,
        description: turn6.actions["final-toast"].description,
        target: { kind: "node", id: 4 },
        build: { kind: "city" },
        useDevelopmentCard: "harvest",
        spend: { grain: 1, ore: 1, wool: 1 },
        pointGain: 3,
        playerLine: turn6.actions["final-toast"].playerLine,
        npcLine: turn6.actions["final-toast"].npcLine,
        recommended: true,
      },
      {
        id: "victory-parade",
        label: turn6.actions["victory-parade"].label,
        description: turn6.actions["victory-parade"].description,
        target: { kind: "road", id: 6 },
        spend: { wood: 1, brick: 1, grain: 1 },
        gain: { ore: 1 },
        pointGain: 3,
        playerLine: turn6.actions["victory-parade"].playerLine,
        npcLine: turn6.actions["victory-parade"].npcLine,
      },
    ],
  },
];
