export const shrimpReward = {
  specialItemId: "grilled_shrimp_plate",
  displayName: "动画烤虾",
};

export const shrimpSceneContent = {
  title: "市场夜钓",
  subtitle: "按 Space 收杆。Perfect 连击会拉高鱼获评分，每局 8 次机会。",
  idleHint: "观察浮标、节奏和鱼的动作，按 Space 收杆。",
  castReadyHint: "继续抛竿：按 Space。",
  castPerfectTitle: "完美命中！",
  castGoodTitle: "中鱼了！",
  castMissTitle: "这杆空了。",
  castContinueLine: "再来一杆，手感正在上来。",
  comboBreakLine: "节奏断了，下一杆重新起势。",
  castTimeoutTitle: "脱钩了！",
  castTimeoutLine: "这杆超时，鱼跑了。",
  sessionSuccessTitle: "今晚收获不错。",
  sessionFailTitle: "今晚也有点收获。",
  sessionQualifiedLine: "进度已达标。",
  sessionNotQualifiedLine: "继续挑战。",
  overlayFound: "鱼获已记录。",
  overlayNormal: "鱼获已记录。",
  overlayExit: "今晚先收竿了，随时可以回来继续钓。",
  qualityLegend: "判定：Perfect / Good / Miss",
  debugPaneTitle: "Fishing Tune",
  economyGainLabel: "本局收益",
  economyCostLabel: "本局成本",
  economyNetLabel: "净收益",
};

export const shrimpSceneTuning = {
  catchZoneStartX: 420,
  catchZoneWidth: 118,
  pointerStartX: 220,
  catchThreshold: 58,
  zoneBounds: {
    min: 310,
    max: 650,
  },
  pointerBounds: {
    min: 200,
    max: 760,
  },
  zoneSpeedPerMs: 0.11,
  pointerSpeedPerMs: 0.24,
  zoneSpeedVariancePerMs: 0.028,
  pointerSpeedVariancePerMs: 0.05,
  catchThresholdVariance: 10,
  catchZoneWidthRange: {
    min: 94,
    max: 140,
  },
  sessionCastCount: 8,
  requiredPrawnTotalForReward: 8,
  resolveRevealDelayMs: 360,
  roundTimeLimitBaseMs: 2300,
  roundTimeLimitMinMs: 1180,
  roundTimeLimitVarianceMs: 620,
  roundTimeLimitTightenPerCastMs: 96,
  roundTimeWarningMs: 650,
  chaosPerCast: 0.085,
  maxChaosFactor: 0.56,
  perfectThreshold: 26,
  scoring: {
    perfectBase: 120,
    goodBase: 72,
    missPenalty: 6,
    comboScoreFactor: 8,
  },
  gradeThresholds: {
    s: 820,
    a: 620,
    b: 420,
  },
  fishRoll: {
    basePrawnChance: 0.04,
    maxPrawnChance: 0.16,
    baseRareFishChance: 0.2,
    maxRareFishChance: 0.38,
  },
  economy: {
    initialCoins: 160,
    baseSessionFee: 10,
    sessionFeeGrowthPerSession: 2,
    sessionFeeGrowthCap: 24,
    castFee: 2,
    timeoutPenaltyFee: 6,
    perfectCatchBonus: 3,
    gradeReward: {
      s: 20,
      a: 10,
      b: 4,
      c: 0,
    },
    fishReward: {
      silverFish: 2,
      carp: 3,
      bass: 4,
      catfish: 6,
      prawn: 10,
    },
  },
  fishBehavior: {
    dartPatternChance: 0.32,
    swayPatternChance: 0.28,
    dartBurstMultiplier: 1.7,
    dartIntervalMinMs: 220,
    dartIntervalMaxMs: 480,
    swayFrequency: 0.011,
    swayAmplitude: 42,
  },
  feedback: {
    flashDurationMs: 130,
    perfectShakeIntensity: 0.0026,
    goodShakeIntensity: 0.0015,
    missShakeIntensity: 0.0019,
    burstCountPerfect: 12,
    burstCountGood: 8,
    burstCountMiss: 5,
  },
};
